spring:
  datasource:
#    url: 'jdbc:mysql://mysqldb:3306/polls_app'
#    username: user
    url: 'jdbc:mysql://localhost:3306/polls_app'
    username: root
    password: '1111'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true